---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: operatingsystemconfigs.operatingsystemmanager.k8c.io
spec:
  group: operatingsystemmanager.k8c.io
  names:
    kind: OperatingSystemConfig
    listKind: OperatingSystemConfigList
    plural: operatingsystemconfigs
    shortNames:
    - osc
    singular: operatingsystemconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OperatingSystemConfig is the object that represents the OperatingSystemConfig
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OperatingSystemConfigSpec represents the operating system
              configuration spec.
            properties:
              bootstrapConfig:
                description: BootstrapConfig is used for initial configuration of
                  machine and to fetch the kubernetes secret that contains the provisioning
                  config.
                properties:
                  files:
                    description: Files is a list of files that should exist in the
                      instance
                    items:
                      description: File is a file that should get written to the host's
                        file system. The content can either be inlined or referenced
                        from a secret in the same namespace.
                      properties:
                        content:
                          description: Content describe the file's content.
                          properties:
                            inline:
                              description: Inline is a struct that contains information
                                about the inlined data.
                              properties:
                                data:
                                  description: Data is the file's data.
                                  type: string
                                encoding:
                                  description: Encoding is the file's encoding (e.g.
                                    base64).
                                  type: string
                              required:
                              - data
                              type: object
                          type: object
                        path:
                          description: Path is the path of the file system where the
                            file should get written to.
                          type: string
                        permissions:
                          default: 644
                          description: Permissions describes with which permissions
                            the file should get written to the file system. Should
                            be in decimal base and without any leading zeroes.
                          format: int32
                          type: integer
                      required:
                      - content
                      - path
                      type: object
                    type: array
                  modules:
                    description: CloudInitModules contains the supported cloud-init
                      modules
                    properties:
                      bootcmd:
                        description: BootCMD module runs arbitrary commands very early
                          in the boot process, only slightly after a boothook would
                          run.
                        items:
                          type: string
                        type: array
                      rh_subscription:
                        additionalProperties:
                          type: string
                        description: RHSubscription registers a Red Hat system either
                          by username and password or activation and org
                        type: object
                      runcmd:
                        description: RunCMD Run arbitrary commands at a rc.local like
                          level with output to the console.
                        items:
                          type: string
                        type: array
                      yum_repo_dir:
                        description: 'YumRepoDir the repo parts directory where individual
                          yum repo config files will be written. Default: /etc/yum.repos.d'
                        type: string
                      yum_repos:
                        additionalProperties:
                          additionalProperties:
                            type: string
                          type: object
                        description: YumRepos adds yum repository configuration to
                          the system.
                        type: object
                    type: object
                  units:
                    description: Units a list of the systemd unit files which will
                      run on the instance
                    items:
                      description: Unit is a systemd unit used for the operating system
                        config.
                      properties:
                        content:
                          description: Content is the unit's content.
                          type: string
                        dropIns:
                          description: DropIns is a list of drop-ins for this unit.
                          items:
                            description: DropIn is a drop-in configuration for a systemd
                              unit.
                            properties:
                              content:
                                description: Content is the content of the drop-in.
                                type: string
                              name:
                                description: Name is the name of the drop-in.
                                type: string
                            required:
                            - content
                            - name
                            type: object
                          type: array
                        enable:
                          description: Enable describes whether the unit is enabled
                            or not.
                          type: boolean
                        mask:
                          description: Mask describes whether the unit is masked or
                            not.
                          type: boolean
                        name:
                          description: Name is the name of a unit.
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  userSSHKeys:
                    description: UserSSHKeys is a list of attached user ssh keys
                    items:
                      type: string
                    type: array
                type: object
              cloudProvider:
                description: CloudProvider represent the cloud provider that support
                  the given operating system version
                properties:
                  name:
                    description: Name represents the name of the supported cloud provider
                    enum:
                    - aws
                    - azure
                    - digitalocean
                    - edge
                    - gce
                    - hetzner
                    - kubevirt
                    - linode
                    - nutanix
                    - openstack
                    - equinixmetal
                    - vsphere
                    - fake
                    - alibaba
                    - anexia
                    - scaleway
                    - baremetal
                    - external
                    - vmware-cloud-director
                    - opennebula
                    type: string
                  spec:
                    description: Spec represents the os/image reference in the supported
                      cloud provider
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - name
                type: object
              osName:
                description: 'OSType represent the operating system name e.g: ubuntu'
                enum:
                - flatcar
                - rhel
                - centos
                - ubuntu
                - amzn2
                - rockylinux
                type: string
              osVersion:
                description: OSVersion the version of the operating system
                type: string
              provisioningConfig:
                description: ProvisioningConfig is used for provisioning the worker
                  node.
                properties:
                  files:
                    description: Files is a list of files that should exist in the
                      instance
                    items:
                      description: File is a file that should get written to the host's
                        file system. The content can either be inlined or referenced
                        from a secret in the same namespace.
                      properties:
                        content:
                          description: Content describe the file's content.
                          properties:
                            inline:
                              description: Inline is a struct that contains information
                                about the inlined data.
                              properties:
                                data:
                                  description: Data is the file's data.
                                  type: string
                                encoding:
                                  description: Encoding is the file's encoding (e.g.
                                    base64).
                                  type: string
                              required:
                              - data
                              type: object
                          type: object
                        path:
                          description: Path is the path of the file system where the
                            file should get written to.
                          type: string
                        permissions:
                          default: 644
                          description: Permissions describes with which permissions
                            the file should get written to the file system. Should
                            be in decimal base and without any leading zeroes.
                          format: int32
                          type: integer
                      required:
                      - content
                      - path
                      type: object
                    type: array
                  modules:
                    description: CloudInitModules contains the supported cloud-init
                      modules
                    properties:
                      bootcmd:
                        description: BootCMD module runs arbitrary commands very early
                          in the boot process, only slightly after a boothook would
                          run.
                        items:
                          type: string
                        type: array
                      rh_subscription:
                        additionalProperties:
                          type: string
                        description: RHSubscription registers a Red Hat system either
                          by username and password or activation and org
                        type: object
                      runcmd:
                        description: RunCMD Run arbitrary commands at a rc.local like
                          level with output to the console.
                        items:
                          type: string
                        type: array
                      yum_repo_dir:
                        description: 'YumRepoDir the repo parts directory where individual
                          yum repo config files will be written. Default: /etc/yum.repos.d'
                        type: string
                      yum_repos:
                        additionalProperties:
                          additionalProperties:
                            type: string
                          type: object
                        description: YumRepos adds yum repository configuration to
                          the system.
                        type: object
                    type: object
                  units:
                    description: Units a list of the systemd unit files which will
                      run on the instance
                    items:
                      description: Unit is a systemd unit used for the operating system
                        config.
                      properties:
                        content:
                          description: Content is the unit's content.
                          type: string
                        dropIns:
                          description: DropIns is a list of drop-ins for this unit.
                          items:
                            description: DropIn is a drop-in configuration for a systemd
                              unit.
                            properties:
                              content:
                                description: Content is the content of the drop-in.
                                type: string
                              name:
                                description: Name is the name of the drop-in.
                                type: string
                            required:
                            - content
                            - name
                            type: object
                          type: array
                        enable:
                          description: Enable describes whether the unit is enabled
                            or not.
                          type: boolean
                        mask:
                          description: Mask describes whether the unit is masked or
                            not.
                          type: boolean
                        name:
                          description: Name is the name of a unit.
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  userSSHKeys:
                    description: UserSSHKeys is a list of attached user ssh keys
                    items:
                      type: string
                    type: array
                type: object
              provisioningUtility:
                default: cloud-init
                description: ProvisioningUtility used for configuring the worker node.
                  Defaults to cloud-init.
                enum:
                - cloud-init
                - ignition
                type: string
            required:
            - bootstrapConfig
            - cloudProvider
            - osName
            - osVersion
            - provisioningConfig
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
