
[[constraint]]
  name = "github.com/heptio/ark"
  version = "0.10.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/pkg/sftp"
  version = "1.10.0"

[[constraint]]
  branch = "master"
  name = "github.com/tmc/scp"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  branch = "release-1.11"
  name = "k8s.io/api"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  revision = "813b1fec840d79b37fe86778237b6db6d1cb959d"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
